Exception: fix exception details when not specified
v2>v3, Because kimchi exception used unicode as msg, convert it to str
       to make unicode encode work.
v1>v2, Add a new type of error to cover general schema validation error.
(per Sheldon's comments)

Not every validation error needs to translate for user,
we define user interested errors,
other developer interested error should report directly by schema validator,
and handled by developer directly.
fix exception handling for this situation.

Signed-off-by: Royce Lv <lvroyce@linux.vnet.ibm.com>
Signed-off-by: Zheng Sheng Zhou <zhshzhou@linux.vnet.ibm.com>